### ISSUE TITLE
An error when add any other non-English language packs

### ISSUE THREAD

**Issue by CiaoPlus** [SimpleMachines/SMF2.1#5497]
#### Description
Add any other non-English language packs

Get an error:

> Refused to execute script from 'http://domain.com/index.php' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

### Steps to reproduce
Admin set the non-English language Locale to "en" or "en-US" .... 
The error no longer appears

I guess there is a bug in the js load function.

`<script src="http://domain.com/index.php"></script> `  was added to `template_javascript`

### Environment (complete as necessary)
- Version/Git revision: 2.1 last git
- Database Type:mysql
- Database Version:10.1
- PHP Version:7.2

### Additional information/references

**Comment by albertlast** [comment]
since already language for non english exists and they got not the issue,
i don't think that this issue is real.

**Comment by CiaoPlus** [comment]
> since already language for non english exists and they got not the issue,
> i don't think that this issue is real.

<html lang="en-US">  is ok
<html lang="it-IT"> and other language Locale get error in Chrome with F12.

**Comment by MissAllSunday** [comment]
Tested  with spanish_latin and couldn't reproduce.

Feel free to create a new issue if someone is able to reproduce this.
